# Generated by Django 2.2.9 on 2020-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='house_area',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='listing',
            name='land_area',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
